apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-a
  namespace: default
  labels:
    app: nginx-a
    testkube.io: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-a
  template:
    metadata:
      labels:
        app: nginx-a
    spec:
      containers:
        - name: nginx
          imagePullPolicy: IfNotPresent
          image: nginx:1.14.2
          ports:
            - containerPort: 80
