name: E2E tests

on:
  [deployment_status] # temporary - it's not possible to get PR events (github.event.pull_request.base.ref), so results for base branch other than dev may be inconsistent

jobs:
  e2e-tests:
    if: github.event.deployment_status.state == 'success' # Run after Vercel preview is deployed
    concurrency: oss-e2e-tests-dev-env # temporary - tests need to be adjusted to allow concurrent execution
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
    - name: Run E2E tests
      uses: kubeshop/testkube-run-action@v1
      with:
        # Instance
        url: https://dev.testkube.io/results/v1
        # Options
        test: dashboard-e2e-tests
        ref: ${{ github.head_ref }}
        variables: |
          BASE_URL="${{ github.event.deployment_status.target_url }}"
          API_URL="testkube-api-server.testkube.svc.cluster.local:8088/v1"